// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package ci

import (
	"bytes"
	"context"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type CIService interface {
	// Parameters:
	//  - Req
	IsTargetRepoUpdated(req *IsTargetRepoUpdatedRequest) (r *IsTargetRepoUpdatedResponse, err error)
	// Parameters:
	//  - Req
	FetchTargetRepoLastCommit(req *FetchTargetRepoLastCommitRequest) (r *FetchTargetRepoLastCommitResonse, err error)
}

type CIServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewCIServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *CIServiceClient {
	return &CIServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewCIServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *CIServiceClient {
	return &CIServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Req
func (p *CIServiceClient) IsTargetRepoUpdated(req *IsTargetRepoUpdatedRequest) (r *IsTargetRepoUpdatedResponse, err error) {
	if err = p.sendIsTargetRepoUpdated(req); err != nil {
		return
	}
	return p.recvIsTargetRepoUpdated()
}

func (p *CIServiceClient) sendIsTargetRepoUpdated(req *IsTargetRepoUpdatedRequest) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("IsTargetRepoUpdated", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := IsTargetRepoUpdatedArgs{
		Req: req,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush(context.Background())
}

func (p *CIServiceClient) recvIsTargetRepoUpdated() (value *IsTargetRepoUpdatedResponse, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error4 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error5 error
		error5 = error4.Read(iprot)
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error5
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "IsTargetRepoUpdated failed: out of sequence response")
		return
	}
	result := IsTargetRepoUpdatedResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

// Parameters:
//  - Req
func (p *CIServiceClient) FetchTargetRepoLastCommit(req *FetchTargetRepoLastCommitRequest) (r *FetchTargetRepoLastCommitResonse, err error) {
	if err = p.sendFetchTargetRepoLastCommit(req); err != nil {
		return
	}
	return p.recvFetchTargetRepoLastCommit()
}

func (p *CIServiceClient) sendFetchTargetRepoLastCommit(req *FetchTargetRepoLastCommitRequest) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("FetchTargetRepoLastCommit", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := FetchTargetRepoLastCommitArgs{
		Req: req,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush(context.Background())
}

func (p *CIServiceClient) recvFetchTargetRepoLastCommit() (value *FetchTargetRepoLastCommitResonse, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error6 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error7 error
		error7 = error6.Read(iprot)
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error7
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "FetchTargetRepoLastCommit failed: out of sequence response")
		return
	}
	result := FetchTargetRepoLastCommitResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type CIServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      CIService
}

func (p *CIServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *CIServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *CIServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func (p *CIServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(context.Background(), seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x9 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x9.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(context.Background())
	return false, x9

}

type cIServiceProcessorIsTargetRepoUpdated struct {
	handler CIService
}

func (p *cIServiceProcessorIsTargetRepoUpdated) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := IsTargetRepoUpdatedArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("IsTargetRepoUpdated", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(context.Background())
		return false, err
	}

	iprot.ReadMessageEnd()
	result := IsTargetRepoUpdatedResult{}
	var retval *IsTargetRepoUpdatedResponse
	var err2 error
	if retval, err2 = p.handler.IsTargetRepoUpdated(args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing IsTargetRepoUpdated: "+err2.Error())
		oprot.WriteMessageBegin("IsTargetRepoUpdated", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(context.Background())
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("IsTargetRepoUpdated", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(context.Background()); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cIServiceProcessorFetchTargetRepoLastCommit struct {
	handler CIService
}

func (p *cIServiceProcessorFetchTargetRepoLastCommit) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := FetchTargetRepoLastCommitArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("FetchTargetRepoLastCommit", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(context.Background())
		return false, err
	}

	iprot.ReadMessageEnd()
	result := FetchTargetRepoLastCommitResult{}
	var retval *FetchTargetRepoLastCommitResonse
	var err2 error
	if retval, err2 = p.handler.FetchTargetRepoLastCommit(args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing FetchTargetRepoLastCommit: "+err2.Error())
		oprot.WriteMessageBegin("FetchTargetRepoLastCommit", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(context.Background())
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("FetchTargetRepoLastCommit", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(context.Background()); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type IsTargetRepoUpdatedArgs struct {
	Req *IsTargetRepoUpdatedRequest `thrift:"req,1" json:"req"`
}

func NewIsTargetRepoUpdatedArgs() *IsTargetRepoUpdatedArgs {
	return &IsTargetRepoUpdatedArgs{}
}

var IsTargetRepoUpdatedArgs_Req_DEFAULT *IsTargetRepoUpdatedRequest

func (p *IsTargetRepoUpdatedArgs) GetReq() *IsTargetRepoUpdatedRequest {
	if !p.IsSetReq() {
		return IsTargetRepoUpdatedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IsTargetRepoUpdatedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IsTargetRepoUpdatedArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = &IsTargetRepoUpdatedRequest{}
	if err := p.Req.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Req, err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("IsTargetRepoUpdated_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:req: %s", p, err)
	}
	if err := p.Req.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Req, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:req: %s", p, err)
	}
	return err
}

func (p *IsTargetRepoUpdatedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IsTargetRepoUpdatedArgs(%+v)", *p)
}

type IsTargetRepoUpdatedResult struct {
	Success *IsTargetRepoUpdatedResponse `thrift:"success,0" json:"success"`
}

func NewIsTargetRepoUpdatedResult() *IsTargetRepoUpdatedResult {
	return &IsTargetRepoUpdatedResult{}
}

var IsTargetRepoUpdatedResult_Success_DEFAULT *IsTargetRepoUpdatedResponse

func (p *IsTargetRepoUpdatedResult) GetSuccess() *IsTargetRepoUpdatedResponse {
	if !p.IsSetSuccess() {
		return IsTargetRepoUpdatedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IsTargetRepoUpdatedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IsTargetRepoUpdatedResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &IsTargetRepoUpdatedResponse{}
	if err := p.Success.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Success, err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("IsTargetRepoUpdated_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *IsTargetRepoUpdatedResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Success, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *IsTargetRepoUpdatedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IsTargetRepoUpdatedResult(%+v)", *p)
}

type FetchTargetRepoLastCommitArgs struct {
	Req *FetchTargetRepoLastCommitRequest `thrift:"req,1" json:"req"`
}

func NewFetchTargetRepoLastCommitArgs() *FetchTargetRepoLastCommitArgs {
	return &FetchTargetRepoLastCommitArgs{}
}

var FetchTargetRepoLastCommitArgs_Req_DEFAULT *FetchTargetRepoLastCommitRequest

func (p *FetchTargetRepoLastCommitArgs) GetReq() *FetchTargetRepoLastCommitRequest {
	if !p.IsSetReq() {
		return FetchTargetRepoLastCommitArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *FetchTargetRepoLastCommitArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchTargetRepoLastCommitArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = &FetchTargetRepoLastCommitRequest{}
	if err := p.Req.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Req, err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("FetchTargetRepoLastCommit_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:req: %s", p, err)
	}
	if err := p.Req.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Req, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:req: %s", p, err)
	}
	return err
}

func (p *FetchTargetRepoLastCommitArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchTargetRepoLastCommitArgs(%+v)", *p)
}

type FetchTargetRepoLastCommitResult struct {
	Success *FetchTargetRepoLastCommitResonse `thrift:"success,0" json:"success"`
}

func NewFetchTargetRepoLastCommitResult() *FetchTargetRepoLastCommitResult {
	return &FetchTargetRepoLastCommitResult{}
}

var FetchTargetRepoLastCommitResult_Success_DEFAULT *FetchTargetRepoLastCommitResonse

func (p *FetchTargetRepoLastCommitResult) GetSuccess() *FetchTargetRepoLastCommitResonse {
	if !p.IsSetSuccess() {
		return FetchTargetRepoLastCommitResult_Success_DEFAULT
	}
	return p.Success
}
func (p *FetchTargetRepoLastCommitResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchTargetRepoLastCommitResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &FetchTargetRepoLastCommitResonse{}
	if err := p.Success.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Success, err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("FetchTargetRepoLastCommit_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *FetchTargetRepoLastCommitResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Success, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *FetchTargetRepoLastCommitResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchTargetRepoLastCommitResult(%+v)", *p)
}
